#!/bin/bash

# Creates 1 GB swap file in /swapfile, designates it as swap, and appends fstab.
# PLEASE NOTE:
# - MUST be ran as root

echo "Your current swap is..."
sudo swapon -s

echo "Making 1 GB swapfile in /"
sudo fallocate -l 4G /swapfile

echo "Changing /swapfile permissions to 600"
sudo chmod 600 /swapfile
sudo ls -la /swapfile

echo "Designating /swapfile as swap file"
sudo mkswap /swapfile
sudo swapon /swapfile
sudo swapon -s

echo "Appending /swapfile to /etc/fstab"
sudo echo "/swapfile none swap sw 0 0" >> /etc/fstab

echo "/etc/fstab now:"
cat /etc/fstab

echo "Finished!"

exit 0
